"""Add playback host and player state fields to Room model

Revision ID: 333ae3a44836
Revises: 795a1c940a8e
Create Date: 2025-08-20 12:22:42.048580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333ae3a44836'
down_revision: Union[str, None] = '795a1c940a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('playback_host_id', sa.UUID(), nullable=True, comment='ID пользователя, который является хостом воспроизведения для этой комнаты.'))
    op.add_column('rooms', sa.Column('active_spotify_device_id', sa.String(), nullable=True, comment='ID активного устройства Spotify хоста воспроизведения.'))
    op.add_column('rooms', sa.Column('current_playing_track_association_id', sa.UUID(), nullable=True, comment='ID записи в очереди (RoomTrackAssociationModel) для текущего играющего трека.'))
    op.add_column('rooms', sa.Column('current_playback_progress_ms', sa.Integer(), nullable=True, comment='Текущий прогресс воспроизведения трека в миллисекундах.'))
    op.alter_column('rooms', 'is_playing',
               existing_type=sa.BOOLEAN(),
               comment='Флаг, указывающий, находится ли плеер в режиме воспроизведения (True) или паузы (False).',
               existing_nullable=False)
    op.create_foreign_key(None, 'rooms', 'users', ['playback_host_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rooms', 'room_track_associations', ['current_playing_track_association_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.alter_column('rooms', 'is_playing',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг, указывающий, находится ли плеер в режиме воспроизведения (True) или паузы (False).',
               existing_nullable=False)
    op.drop_column('rooms', 'current_playback_progress_ms')
    op.drop_column('rooms', 'current_playing_track_association_id')
    op.drop_column('rooms', 'active_spotify_device_id')
    op.drop_column('rooms', 'playback_host_id')
    # ### end Alembic commands ###
