"""add created_at room

Revision ID: 382c10104ec1
Revises: 21ce24baa75a
Create Date: 2025-07-27 19:37:43.115939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382c10104ec1'
down_revision: Union[str, None] = '21ce24baa75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'room_track_association', 'users', ['addded_by_user_id'], ['id'])
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    op.create_unique_constraint(None, 'rooms', ['id'])
    op.create_unique_constraint(None, 'tracks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tracks', type_='unique')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_column('rooms', 'created_at')
    op.drop_constraint(None, 'room_track_association', type_='foreignkey')
    # ### end Alembic commands ###
