"""new field role

Revision ID: 4f41cbd6ec2d
Revises: 52172d047b7a
Create Date: 2025-08-10 14:30:48.423489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f41cbd6ec2d'
down_revision: Union[str, None] = '52172d047b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_room_association', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_room_association', 'role')
    # ### end Alembic commands ###
