"""Fix table Room

Revision ID: 57f100e1c658
Revises: 333ae3a44836
Create Date: 2025-08-21 16:47:02.150825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f100e1c658'
down_revision: Union[str, None] = '333ae3a44836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'is_playing',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг, указывающий, находится ли плеер в режиме воспроизведения (True) или паузы (False).',
               existing_nullable=False)
    op.drop_column('rooms', 'current_playback_progress_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('current_playback_progress_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='Текущий прогресс воспроизведения трека в миллисекундах.'))
    op.alter_column('rooms', 'is_playing',
               existing_type=sa.BOOLEAN(),
               comment='Флаг, указывающий, находится ли плеер в режиме воспроизведения (True) или паузы (False).',
               existing_nullable=False)
    # ### end Alembic commands ###
