"""new table Ban

Revision ID: 599d7edaaa99
Revises: 4f41cbd6ec2d
Create Date: 2025-08-12 13:41:44.048572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599d7edaaa99'
down_revision: Union[str, None] = '4f41cbd6ec2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ban_user_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ban_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('by_ban_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ban_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['by_ban_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bans')
    # ### end Alembic commands ###
