"""Refine Ban model relationships

Revision ID: 6e74286a8788
Revises: f03eb68f7eb5
Create Date: 2025-08-13 11:53:11.778343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e74286a8788'
down_revision: Union[str, None] = 'f03eb68f7eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friendships', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='unique')
    # ### end Alembic commands ###
