"""update room track

Revision ID: f3eba9a91266
Revises: 382c10104ec1
Create Date: 2025-07-30 12:44:07.518962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3eba9a91266'
down_revision: Union[str, None] = '382c10104ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_track_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('order_in_queue', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('room_track_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_track_association',
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_in_queue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('addded_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['addded_by_user_id'], ['users.id'], name='room_track_association_addded_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='room_track_association_room_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='room_track_association_track_id_fkey'),
    sa.PrimaryKeyConstraint('room_id', 'track_id', name='room_track_association_pkey')
    )
    op.drop_table('room_track_associations')
    # ### end Alembic commands ###
